version: '3.8'

services:
  app:
    build: .
    container_name: my_app
    env_file: 
      - .env 
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "npm run migrate:dev && npm run dev"

  db:
    image: postgres:16
    container_name: my_db
    env_file: 
      - .env 
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  test:
    build: .
    container_name: my_test
    env_file: 
      - .env
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "npm test"

volumes:
  db_data:
